# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Docs Italia
description: Documenti pubblici, digitali.
author: Team Digitale e AgID
twitter:
  username: developersITA

email: teamdigitale@governo.it
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.italia.it"
twitter_username: developersITA
github_username:  italia

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: AgID
owner_full: Agenzia per l'Italia Digitale
owner_link: http://www.agid.gov.it
logo: /assets/icons/logo-it.png
owner_logo: /assets/images/logo-agid.svg
partner_short: Team Digitale
partner_full: Team per la Trasformazione Digitale
partner_link: https://teamdigitale.governo.it
privacy_link: https://developers.italia.it/it/privacy-policy
gov_logo: /assets/images/governo.svg
partner_logo: /assets/images/dt-logo.svg
pill: beta
lang: it
piwik: 9966c07e-e545-4281-8558-a5ad707c5c52

collections:
  pages:
    output: true
    permalink: /:path/
    layout: page
  projects:
    output: false
